name: Wine-Git WoW64 CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.h', 'configure', '**/*.in', 'Makefile.am', 'Makefile.in') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y debootstrap perl git wget xz-utils bubblewrap autoconf ccache

      - name: Configure ccache
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          ccache -M 5G  # Set maximum cache size to 5GB
          ccache -s

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt

      - name: Build Wine
        run: |
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          chmod +x build_wine.sh
          export TERMUX_GLIBC="true"
          export EXPERIMENTAL_WOW64="true"
          export WINE_VERSION="git"
          export USE_CCACHE="true"  # Enable ccache usage
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache  # Set ccache directory inside the repository
          export PATH="/usr/lib/ccache:$PATH"  # Ensure ccache is in the PATH

          WINE_BRANCH=vanilla ./build_wine.sh
          WINE_BRANCH=staging ./build_wine.sh

          ccache -s
          sha256sum *.tar.xz

      - uses: actions/upload-artifact@v4
        with:
          name: Wine-Git
          path: ./*.tar.xz
