name: Wine-Git WoW64 Proot CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          chmod +x build_wine.sh
          export EXPERIMENTAL_WOW64="true"
          export WINE_VERSION="git"
          export TERMUX_GLIBC="false"
          export TERMUX_PROOT="true"
          WINE_BRANCH=vanilla ./build_wine.sh
          WINE_BRANCH=staging ./build_wine.sh
          sha256sum *.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: Wine-Git-WoW64-Proot
          path: ./*.tar.xz
